Adiciona fastlane. Adiciona slather. Atualiza ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,15 +2,19 @@ name: CI
 
 on:
   push:
-    branches: [ develop ]
+    branches: 
+      - develop
   pull_request:
-    branches: [ develop ]
+    branches:
+      - develop
+      - feature/**
+      - hotfix/**
+      - bugfix/**
 
 jobs:
   build:
-    name: Build and Test default scheme using any available iPhone simulator
+    name: Build
     runs-on: macos-latest
-
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -20,23 +24,78 @@ jobs:
           default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
           echo $default | cat >default
           echo Using default scheme: $default
-      - name: Build
-        env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
+      - name: Install Dependencies
         run: |
-          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
-      - name: Test
-        env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
+          export LC_ALL=en_US.UTF-8
+          export LANG=en_US.UTF-8
+          sudo xcode-select -s /Applications/Xcode.app
+          xcodebuild -sdk -version
+          rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache
+          bundle --version
+          export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
+          rm -fR ~/.gem
+          rbenv install -s # It will get ".ruby-version" file and skip silently if already exists.
+          gem install bundler
+          ruby -v
+          bundle update --bundler
+          bundle install --path ~/.gem
+          bundle exec pod install
+          brew install swiftlint
+          chmod +x scripts/run_swiftlint.sh
+          chmod +x scripts/xcov-to-sonarqube-generic.sh
+      - name: Xcode Build
         run: |
-          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
+          set -o pipefail
+          xcodebuild build -workspace CsBootcamp.xcworkspace -scheme 'CsBootcamp' CODE_SIGNING_ALLOWED=NO | xcpretty
+
+  swiftlint:
+    needs: build
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: SwiftLint
+        run: |
+          ./Pods/SwiftLint/swiftlint --strict
+
+  test:
+    needs: [build, swiftlint]
+    runs-on: macos-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+      - name: Fetch all branches
+        run: |
+          git fetch --prune --unshallow
+      - name: Run Tests
+        run: |
+          set -o pipefail
+          gem install bundler:1.16.6
+          bundle install
+          bundle exec fastlane tests
+      - name: Convert Logs
+        run: |
+          scripts/xcov-to-sonarqube-generic.sh build/Logs/Test/Run-covidwatch-ios-* > coverage.xml
+      - name: Install SonarCloud
+        run: |
+          export SONAR_SCANNER_VERSION=4.2.0.1873
+          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-macosx.zip
+          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
+      - name: Run SonarQube
+        env:
+          SONARCLOUD_LOGIN_KEY: ${{ secrets.SONARCLOUD_LOGIN_KEY }}
+        run: |
+          export SONAR_SCANNER_VERSION=4.2.0.1873
+          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-macosx
+          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
+          export SONAR_SCANNER_OPTS="-server"
+          sonar-scanner \
+          -Dsonar.organization=covid19risk \
+          -Dsonar.projectKey=covid19risk_covidwatch-ios \
+          -Dsonar.sources="CsBootcamp" \
+          -Dsonar.host.url=https://sonarcloud.io \
+          -Dsonar.login=$SONARCLOUD_LOGIN_KEY \
+          -Dsonar.branch.name=develop \
+          -Dsonar.c.file.suffixes=- \
+          -Dsonar.cpp.file.suffixes=- \
+          -Dsonar.objc.file.suffixes=- \
+          -Dsonar.coverageReportPaths=coverage.xml
